#############################################################################
# Makefile for building: SP-Elevator-Controller-System
# Generated by qmake (2.01a) (Qt 4.8.3) on: Fri Nov 16 23:13:07 2012
# Project:  SP-Elevator-Controller-System.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.3/bin/qmake -o Makefile SP-Elevator-Controller-System.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.3/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.3/include/QtCore -I/usr/local/Trolltech/Qt-4.8.3/include/QtGui -I/usr/local/Trolltech/Qt-4.8.3/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.3/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.3/lib -lQtGui -L/usr/local/Trolltech/Qt-4.8.3/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		request.c \
		error.c \
		elevator.c \
		action.c \
		FunctionQueue/fqueue.c \
		outsidedialog.cpp moc_mainwindow.cpp \
		moc_outsidedialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		request.o \
		error.o \
		elevator.o \
		action.o \
		fqueue.o \
		outsidedialog.o \
		moc_mainwindow.o \
		moc_outsidedialog.o
DIST          = /usr/local/Trolltech/Qt-4.8.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/include_source_dir.prf \
		SP-Elevator-Controller-System.pro
QMAKE_TARGET  = SP-Elevator-Controller-System
DESTDIR       = 
TARGET        = SP-Elevator-Controller-System

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_outsidedialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SP-Elevator-Controller-System.pro  /usr/local/Trolltech/Qt-4.8.3/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.3/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.3/lib/libQtCore.prl
	$(QMAKE) -o Makefile SP-Elevator-Controller-System.pro
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.3/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.3/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.3/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile SP-Elevator-Controller-System.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SP-Elevator-Controller-System1.0.0 || $(MKDIR) .tmp/SP-Elevator-Controller-System1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SP-Elevator-Controller-System1.0.0/ && $(COPY_FILE) --parents mainwindow.h request.h error.h elevator.h data.h action.h FunctionQueue/fqueue.h outsidedialog.h .tmp/SP-Elevator-Controller-System1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp request.c error.c elevator.c action.c FunctionQueue/fqueue.c outsidedialog.cpp .tmp/SP-Elevator-Controller-System1.0.0/ && $(COPY_FILE) --parents mainwindow.ui outsidedialog.ui .tmp/SP-Elevator-Controller-System1.0.0/ && (cd `dirname .tmp/SP-Elevator-Controller-System1.0.0` && $(TAR) SP-Elevator-Controller-System1.0.0.tar SP-Elevator-Controller-System1.0.0 && $(COMPRESS) SP-Elevator-Controller-System1.0.0.tar) && $(MOVE) `dirname .tmp/SP-Elevator-Controller-System1.0.0`/SP-Elevator-Controller-System1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SP-Elevator-Controller-System1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_outsidedialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_outsidedialog.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/local/Trolltech/Qt-4.8.3/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_outsidedialog.cpp: outsidedialog.h
	/usr/local/Trolltech/Qt-4.8.3/bin/moc $(DEFINES) $(INCPATH) outsidedialog.h -o moc_outsidedialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_outsidedialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_outsidedialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Trolltech/Qt-4.8.3/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_outsidedialog.h: outsidedialog.ui
	/usr/local/Trolltech/Qt-4.8.3/bin/uic outsidedialog.ui -o ui_outsidedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		outsidedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

request.o: request.c request.h \
		data.c \
		data.h \
		FunctionQueue/fqueue.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o request.o request.c

error.o: error.c error.h \
		data.c \
		data.h \
		FunctionQueue/fqueue.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o error.o error.c

elevator.o: elevator.c elevator.h \
		data.c \
		data.h \
		FunctionQueue/fqueue.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o elevator.o elevator.c

action.o: action.c action.h \
		data.c \
		data.h \
		FunctionQueue/fqueue.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o action.o action.c

fqueue.o: FunctionQueue/fqueue.c FunctionQueue/fqueue.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fqueue.o FunctionQueue/fqueue.c

outsidedialog.o: outsidedialog.cpp outsidedialog.h \
		ui_outsidedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o outsidedialog.o outsidedialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_outsidedialog.o: moc_outsidedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_outsidedialog.o moc_outsidedialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

